matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        bundler: true
        yarn: true
        directories:
          - node_modules
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      sudo: required
      before_install:
        - nvm install 8
        - yarn
        - cd android
        - rvm install ruby-2.3.0
        - bundle install
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - fastlane build
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      cache:
        bundler: true
        yarn: true
        directories:
          - node_modules
      before_install:
        - nvm install 8
        - brew install yarn --ignore-dependencies
        - yarn
        - cd ios
        - rvm install ruby-2.3.0
        - bundle install
        - pod install
      script:
        - fastlane build
